### ISSUE TITLE
replacetokens yaml  Azure pipeline: The task name replacetokens is ambiguous.

### ISSUE THREAD

**Issue by tedsluis** [qetza/vsts-replacetokens-task#107]
I am using the *vsts-replacetokens-task* for quite some time in Azure Devops pipelines. 
It works just great!
Now I am moving over to Azure pipelines in YAML. Doing that, I run into error when using the  *vsts-replacetokens-task*:

```
"Job DeployJob: Step task reference is invalid. The task name replacetokens is ambiguous. 
Specify one of the following identifiers to resolve the ambiguity: 
a8515ec8-7254-4ffd-912c-86772e2b5962, 9240b5c1-a1b2-4799-9325-e071c63236fb"
```
There are two *VSTS tasks* using the same task name and this causes the issue!

Down here my example pipeline with the *vsts-replacetokens-task*:
```yaml
stages:  
- stage: 'DeployStage'
  jobs:
  - job: 'DeployJob'
    pool:
      name: 'Build-Azure-Windows'
    steps:
    - task: replacetokens@3
      inputs:
        rootDirectory: 'c:\files'
        targetFiles: 'parameters.json' 
        encoding: 'ascii'
        actionOnMissing: 'warn'
        keepToken: false
        tokenPrefix: '#{'
        tokenSuffix: '}#'
```

When I change the task name *replacetokens@3* to *a8515ec8-7254-4ffd-912c-86772e2b5962* it works. Would it be possible to change the replacetokens task name to a unique name?
