### ISSUE TITLE
replace token yml task

### ISSUE THREAD

**Issue by AjeetChouksey** [qetza/vsts-replacetokens-task#116]
I am using replace token yml task. Task executed with error but it's not replacing the values. Whereas same is working when I execute using UI (Classic) task.

            - task: replacetokens@3
              displayName: 'replace token' 
              inputs:
                targetFiles: '**/*main*.js'
                rootDirectory: '$(Pipeline.Workspace)/${{parameters.artifact}}/'
                encoding: 'auto'
                escapeType: none
                writeBOM: true
                actionOnMissing: 'warn'
                keepToken: false
                tokenPrefix: '#{'
                tokenSuffix: '}#'

**Comment by qetza** [comment]
Hi @AjeetChouksey,
Could you enable detailed logs and see if there is not an issue with the supplied inputs? As in the input `rootDirectory` you are using yaml templating parameters.

**Comment by AdamRiddick** [comment]
Hi @qetza,

I've hit this as well. Everything was fine until I added the rootDirectory input, which is a parameter;

```- task: replacetokens@3
    condition: succeeded()
    displayName: 'Replace Tokens'
    inputs:
      rootDirectory: $(Build.ArtifactStagingDirectory)
      targetFiles: '**/*.json'
      actionOnMissing: 'warn'
      keepToken: false
      tokenPrefix: '#{'
      tokenSuffix: '}#'
      verbosity: 'detailed'
```

I also tried `rootDirectory: '$(Build.ArtifactStagingDirectory)'`

Either way, the detailed logs show;

##[section]Starting: Replace Tokens
==============================================================================
Task         : Replace Tokens
Description  : Replace tokens in files
Version      : 3.2.1
Author       : Guillaume Rouchon
Help         : v3.2.1 - [More Information](https://github.com/qetza/vsts-replacetokens-task#readme)
==============================================================================
pattern: #\{((?:(?!\}#).)*)\}#
##[section]Finishing: Replace Tokens

**Comment by qetza** [comment]
Hi @AdamRiddick,
I don't see anything special with your configuration, i've done a test with the following YAML:

```
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace Tokens'
  inputs:
    rootDirectory: '$(Build.ArtifactStagingDirectory)'
    targetFiles: '**/*.json'
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    verbosity: 'detailed'
```
and didn't get any issues.

Could you do a run with system diagnostics enabled and share the logs?
