### ISSUE TITLE
Single Quotes of Variables

### ISSUE THREAD

**Issue by winnieshen96** [qetza/vsts-replacetokens-task#124]
When using a job variable to replace, the replaced value includes the single quote. 

For example, if the variable is url: 'http://123', and in the json file, #{url}#/345 will become 'http://123'/345, which is not a valid url because of the single quotes.

I have tried adding escape character ' in the task settings, but the task seems to ignore it and still replaces with the single quotes.

I have tried escape Type of auto and json, neither of them helped.

**Comment by qetza** [comment]
Hi @winnieshen96,

Are you using the UI to define your variable or in YAML file? Do you put the single quotes in your variable value?

The task is using the SDK function to get a value of a variable based on its name and is doing nothing to the value (except encoding if you have configure it)

**Comment by winnieshen96** [comment]
I define the variable in YAML file. Is that the reason why it has single quotes?

**Comment by qetza** [comment]
Could you share your YAML file (or a file to repro) as i've tested with the following file and couldn't repro the issue:
```
pool:
  vmImage: ubuntu-16.04

variables:
  url: 'http://123'

steps:
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'replace tokens'
  inputs:
    rootDirectory: 'issue-124'
    targetFiles: '**/*.json'
    verbosity: detailed
```
