### ISSUE TITLE
Replace token from job template (change variable/parameter scope)

### ISSUE THREAD

**Issue by shahnm** [qetza/vsts-replacetokens-task#125]
Hi,

I want to use this task to replace tokens but I would like to do it from a job template and have the task use the templates variables instead of the pipeline variables.
Basically I don't want to use the $(myVariable) but rather ${{ parameters.myVariable }}

I can't find anywhere to configure this and it doesn't see to work by default.

**Comment by qetza** [comment]
Hi @shahnm,
Template parameters are expanded before the pipeline runs: the templating runtime is first run to generate a normal yaml file then this file is run on the agent so tasks doesn't know about template parameters as they were already replaced by their values.

One solution i think to your issue is to declare in your template local variables and assign them the parameters:

```yaml
parameters:
  myVariable: ''
jobs:
- job: myjob
  variables:
    myVariable: ${{ parameters.myVariable }}
  steps:
  - task: qetza.replacetokens.replacetokens-task.replacetokens@3
    inputs:
      targetFiles: '**/*.json'
```
In your file you then use the token `#{myVariable}#`

Note: i didn't have the time to test the proposed solution but it should work :-)
