### ISSUE TITLE
Receiving Ambiguous error

### ISSUE THREAD

**Issue by clifpi01** [qetza/vsts-replacetokens-task#132]
Greetings, 
My parameters are the following;
- task: replacetokens@3
      displayName: 'Replace tokens in main.tf file'
      inputs:
        rootDirectory: '$(Build.ArtifactStagingDirectory)'
        targetFiles: '**/main.tf'
        escapeType: none
        tokenPrefix: '__'
        tokenSuffix: '__'

and I am receiving the following error
Job BuildConfig: Step  task reference is invalid. The task name replacetokens is ambiguous. Specify one of the following identifiers to resolve the ambiguity: a8515ec8-7254-4ffd-, 9240b5c1-a1b2-

Just trying to figure out if I have the command correct or not. Thank you.

**Comment by qetza** [comment]
Hi @clifpi01,
You need to use the fully qualified name for nosn microsoft extensions:

```yaml
task: qetza.replacetokens-dev.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in main.tf file'
  inputs:
    rootDirectory: '$(Build.ArtifactStagingDirectory)'
    targetFiles: '**/main.tf'
    escapeType: none
    tokenPrefix: ''
    tokenSuffix: ''
```
