### ISSUE TITLE
Replace Tokens to support multi-line strings

### ISSUE THREAD

**Issue by ZeChArtiahSaher** [qetza/vsts-replacetokens-task#140]
Sometimes I find it useful to be able to parse multiline strings:
```
variables:
   large-comment-block: |
      # Purpose: Replace tokens in configs with azure pipelines variables
      # 
      # Example:
      #   sample.config
      #   -------------------------------
      #        KEY1: #{INSERT_VALUE_HERE}#
      # 
```

Current behavior of substitution would only result in: `# Purpose: Replace tokens in configs with azure pipelines variables`.

**Comment by qetza** [comment]
Hi @ZeChArtiahSaher,
Thanks for reporting the issue, I'll see if i can fix it.

**Comment by ZeChArtiahSaher** [comment]
This is my latest use-case that failed:

```
  - template: templates/replace-tokens.s.yml
    parameters:
      targetFiles: |
        ${{ parameters['Pipelines.Directory'] }}/${{ project.value['Pipeline'] }}.yml => $(Build.SourcesDirectory)/${{ project.value['Repository.Name'] }}/deploy/azure-pipelines.g.yml
      tokenPrefix: '###{'
      tokenSuffix: '}###'
```

```
parameters:
  targetFiles:     ''
  tokenPrefix:     '#{'
  tokenSuffix:     '}#'

steps:
  - task: qetza.replacetokens.replacetokens-task.replacetokens@3
    displayName: Replace Tokens
    inputs:
      targetFiles: ${{ parameters.targetFiles }}
      tokenPrefix: ${{ parameters.tokenPrefix }}
      tokenSuffix: ${{ parameters.tokenSuffix }}
```
