### ISSUE TITLE
Unable to replace tokens in file when using multi-stage yml pipelines

### ISSUE THREAD

**Issue by ra-hulk** [qetza/vsts-replacetokens-task#154]
I am using build and release definitions as code (as shown [here](https://docs.microsoft.com/en-us/learn/modules/create-a-build-pipeline/8-build-multiple-configurations#define-the-template)).

Just like the example above, I have two .yml files (azure-pipelines.yml and templates/build.yml). The replace token task is part of the latter file.

The tokens I wish to replace are being passed from the parent file (azure-pipelines.yml) as **parameters** in the build.yml file (this file only supports parameters, not variables, as mentioned in the example above). 

When running the tasks, I get this error - `##[error]  variable not found: sometoken`

Please see my configuration below -
**appsettings.json** (file containing the token)
```json
"object": {
      "field1": "#{sometoken}#"
}
````

**azure-pipelines.yml**

```yml
- stage: 'Dev'
  displayName: 'Dev'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    pool: 
      name: Hosted VS2017
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/build.yml
            parameters:
              sometoken: somevalue
```
**templates/build.yml**

````yml
parameters:
- name: sometoken
  default: ''

steps:
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in **/appsettings.json'
  inputs:
    rootDirectory: '$(System.ArtifactsDirectory)/drop/api'
    targetFiles: '**/appsettings.json'
    encoding: auto
    writeBOM: true
    escapeType: auto
    verbosity: detailed
    actionOnMissing: fail

````
Upon checking the task logs, I can see the target file was found. However, it failed to replace the token.

Thank you.

**Comment by jdkemme** [comment]
Is your example different than what you're actually trying to run?  I just mocked this up quick, and with your variable 'sometoken' defined at the stage level, the deployment job uses it and replaces it in the file as expected.  There is no need to use parameters to 'pass' variables to files.  Templates during parse time are all mashed up into one resulting yaml definition.  Whats important is variable scope (defined at stage, job, or step level) and boundaries (variables cannot be passed between stages, output vars must be used to share between jobs, etc).

**Comment by ra-hulk** [comment]
@jdkemme thanks, that worked. I ended up moving the declaration of the token in the variables section. My **azure-pipelines.yml** ended up looking something like this
````yml
- stage: 'Dev'
  displayName: 'Dev'
  dependsOn: Build
  variables:
    sometoken: somevalue
  jobs:
  - deployment: Deploy
    pool: 
      name: Hosted VS2017
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/build.yml
````
