### ISSUE TITLE
Replacement issue

### ISSUE THREAD

**Issue by ashishnm** [qetza/vsts-replacetokens-task#159]
I may be using wrong configurations. Please help out for right solutions.

I am trying to use replace tokens as below.

Do you see any configuration issue as below

steps: - task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in **/*.config **/*.json'
  inputs:
    targetFiles: |
     **/*.config
     **/*.json
    verbosity: detailed
    tokenPrefix: '{'
    tokenSuffix: '}'

**log as below**

2020-05-11T18:44:01.6149125Z ##[section]Starting: Replace tokens in **/*.config **/*.json
2020-05-11T18:44:01.6363261Z ==============================================================================
2020-05-11T18:44:01.6363986Z Task         : Replace Tokens
2020-05-11T18:44:01.6364452Z Description  : Replace tokens in files
2020-05-11T18:44:01.6364873Z Version      : 3.6.0
2020-05-11T18:44:01.6365252Z Author       : Guillaume Rouchon
2020-05-11T18:44:01.6365919Z Help         : v3.6.0 - [More Information](https://github.com/qetza/vsts-replacetokens-task#readme)
2020-05-11T18:44:01.6366694Z ==============================================================================
2020-05-11T18:44:02.2020864Z pattern: \{\s*((?:(?!\{)(?!\s*\}).)*)\s*\}
2020-05-11T18:44:02.2247835Z replaced 0 tokens out of 0 in 0 file(s) in 0.04 seconds.
2020-05-11T18:44:03.1202699Z ##[section]Finishing: Replace tokens in **/*.config **/*.json
Library value

**myhello = Hello**

Value in appsettngs.config

**<section name="{myhello}" type="Exceptionless.ExceptionlessSection, Exceptionless" />**

**Comment by qetza** [comment]
Hi @ashishnm,
I think your issue is in the target file syntax, try this:
```
steps:
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in **/*.config **/*.json'
  inputs:
  targetFiles: |
    **/*.config
    **/*.json
  verbosity: detailed
  tokenPrefix: '{'
  tokenSuffix: '}'
```
