### ISSUE TITLE
Azure Devops Release Pipeline variables

### ISSUE THREAD

**Issue by Danielovich** [qetza/vsts-replacetokens-task#199]
Hi :)

Not sure how I can get this to work, and I have failed so far.

I have a release pipeline with a variable named "foo" and the value of "bar".

In my manifest.yaml I have:

```
    spec:
      containers:
        - name: frost-rss-web
          image: danielfrostdk/frostrss:${foo}
```

When I run the task my expectation was that ${foo} would be replaced to 

```
    spec:
      containers:
        - name: frost-rss-web
          image: danielfrostdk/frostrss:bar
```

But I can't seem to make that happen. 

And on the same note, is the file being worked on for repleacements called the same after the task is done ?

So that I can expect that my file is not named something else after the replacement task ? 

Thank you very much!
