### ISSUE TITLE
How to pass parameters to template?

### ISSUE THREAD

**Issue by flmmartins** [qetza/vsts-replacetokens-task#202]
Hello, 

I am building a template that make uses of the replacetokens in myfile and replaces to the correct variable. I always have to make the following

This is my dummy file as example and I want to replace myVar with a content:
```
__myVar__ 
```

azure-pipeline.yml
```
variables:
- name: myVar
   value: mycontent

stages:
- template: this_job_replaces_tokens_in_myfile_and_do_stuff.yml
   parameters: 
       file: ./myfile
```

If I do the above it works but I wanted to do avoid creating a var and use a template parameter like:

azure-pipeline.yml

```
stages:
- template: this_job_replaces_tokens_in_myfile_and_do_stuff.yml
   parameters: 
       file: ./myfile
       myVar: mycontent
```

Is this even possible?

**Comment by qetza** [comment]
Hi @flmmartins,
Template parameters and variables are not the same in the Azure Pipelines engine. Template parameters are "string tokens" that are replaced by there value before executing the pipeline so tasks do not know about parameters. (https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runs?view=azure-devops#process-the-pipeline)
One thing you could try is moving the declaration of the variable in your template and assign it the value of the parameter:

```yaml
variables:
- name: myVar
  value: ${{ parameters.myVar }}
```
