### ISSUE TITLE
Variables replacements add a single quote

### ISSUE THREAD

**Issue by ccyoucc** [qetza/vsts-replacetokens-task#222]
Hello,
I am using the task replace tokens with this configuration 
```
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
              displayName: 'Replace tokens'
              inputs:
                rootDirectory: '$(Pipeline.Workspace)/$(artifact_name)'
                targetFiles: |
                  **/*.yml                
                encoding: 'utf-8'
                tokenPrefix: '__'
                tokenSuffix: '__'
                actionOnMissing: 'warn'
                keepToken: false
                verbosity: 'detailed'
                actionOnNoFiles: 'continue'
                enableTransforms: false
                useLegacyPattern: false
                enableTelemetry: false
```

and after the replacement takes place in azure deployment pipeline, a single quote is added to the value (the value comes from a keyvault).
This is a random behavior, because if I make another deployment, with the same artifact, the single quote is no more added to my values.

**Source File Before:**
```
spring:
  datasource:
    url: jdbc:mariadb://__maria_db_server_name__.mariadb.database.azure.com:3306/__maria_db_database_name__?useSSL=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: __maria_db_server_login__
    password: __maria_db_server_password__
  mail:
     host: __smtp_host__
    port: __smtp_port__
    username: __smtp_login__
    password: __smtp_password__
    properties:
      mail:
        smtp:
          ssl:
            enable: __smtp_use_ssl__
```

**Source File After:**
```
spring:
  datasource:
    url: jdbc:mariadb://[myvalue]'.mariadb.database.azure.com:3306/[myvalue]'?useSSL=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: [myvalue]'
    password: [myvalue]'
  mail:
     host: [myvalue]
    port: [myvalue]
    username: 
    password: 
    properties:
      mail:
        smtp:
          ssl:
            enable: [myvalue]'
```

I have searched in the source code of the task, but nothing appeared to be wrong with it. 
Please let me know if you have an idea, of what I can search in order to fix this problem.

Best regards,
Constantin
