### ISSUE TITLE
Replace token in main.js throws warning

### ISSUE THREAD

**Issue by annitannenbaum** [qetza/vsts-replacetokens-task#225]
Hi,

I'm getting a warning when attempting to replace a URL inside my main.js:

![image](https://user-images.githubusercontent.com/57633190/137861259-702ae92a-83bd-4ac0-8329-bf0543467142.png)

My YAML looks like this:

steps:
```
- task: qetza.replacetokens.replacetokens-task.replacetokens@2
  displayName: 'Replace tokens in main*.js'
  inputs:
    rootDirectory: '$(System.DefaultWorkingDirectory)/artifact/drop/web'
    targetFiles: 'main*.js'
    encoding: 'utf-8'
    tokenPrefix: '###'
    tokenSuffix: '###'
```
    
Curiously, it worked with all previous builds and there was no code change to the file where the token is replaced.
