### ISSUE TITLE
target path not working?

### ISSUE THREAD

**Issue by andrea-cassioli-maersk** [qetza/vsts-replacetokens-task#226]
I am running a replacement task as part of a pipeline as follow

```       
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
        displayName: 'Replace tokens'
        inputs:
          rootDirectory: .
          targetFiles: |
            infrastructure/ingress/*.yaml => ./*.tmp.yaml
          actionOnMissing: fail
          tokenPrefix: '${'
          tokenSuffix: '}'
```

The substitution works, but the output files are not in `./` but rather in `infrastructure/ingress/`.

Am I missing anything?
