### ISSUE TITLE
Support parameters in yaml pipelines

### ISSUE THREAD

**Issue by kwaazaar** [qetza/vsts-replacetokens-task#237]
When using parameters in a yaml pipeline, they do not become part of the variables-set. It would be nice if parameters would also be supported. Eg:

``` yaml
parameters:
  - name: param1
    type: string
    default: `abc`

variables:
  - name: var1
    value: 'xyz`
```

#{param1}# resolves to 'abc' and #{var1}# resolves to 'xyz'.

I can workaround this issue, but defining variables that refer to parameters, but that's a lot more trouble.
