### ISSUE TITLE
No warning in pipeline summary if tokens not found

### ISSUE THREAD

**Issue by Philippe85** [qetza/vsts-replacetokens-task#246]
In a Azure DevOps pipeline, I use your task wtih the parameter "actionOnMissing" with the "log warning" value.
But when all tokens are not replaced :
![image](https://user-images.githubusercontent.com/25458469/149372733-b7c0ad19-08cb-4d00-9e2d-bcc14381e448.png)
I don't see warnings on tokens not found in the pipeline run summury in Azure DevOps !!!
How to be alerted if we don't see warning ?

**Comment by qetza** [comment]
Hi @Philippe85,
Could you share all your configuration as i cannot reproduce the issue:
![image](https://user-images.githubusercontent.com/8191369/149489427-0289c26a-3eac-491b-b84c-2326e4cedf5d.png)

This was with the following configuration:
```yaml
- task: qetza.replacetokens.replacetokens-task.replacetokens@4
  displayName: 'replace tokens'
  inputs:
    rootDirectory: 'issue-246'
    targetFiles: test.txt
```

**Comment by Philippe85** [comment]
I use this task :
```
steps:
- task: replacetokens@3
  displayName: Update configuration values
  inputs:
    targetFiles: ${{ parameters.TargetFiles }}
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'log warning'
    actionOnNoFiles: 'fail'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    useLegacyPattern: false
    enableTransforms: false
    enableTelemetry: false
```
And when I click on the Azure DevOps Pipeline Run, in the tab "Summary", I see warnings, but none on missing tokens. To see the ReplaceTokens task warnings, I need to rerun the pipeline in debug mode and need to go in task log. But to do that, I need to know there are missing tokens !
