### ISSUE TITLE
replaced 0 tokens out of 0 in 0 file(s) in 0.015 seconds.

### ISSUE THREAD

**Issue by iomdesign** [qetza/vsts-replacetokens-task#248]
I've got variable tokens like the following in my web.config file

```<add name="someSQLConnection" connectionString="${SQLConnectionToken}" providerName="System.Data.SqlClient" />```

Which works in dev with user secrets. Then in my Azure DevOps release pipeline (using GUI) I've got the replace tokens task configured like:

```
steps:
- task: qetza.replacetokens.replacetokens-task.replacetokens@4
  displayName: 'Replace variable tokens'
  inputs:
    rootDirectory: '$(System.DefaultWorkingDirectory)/PipelineName/ArtifactName/SomeWebDeployPackage.zip'
    tokenPattern: custom
    tokenPrefix: '${'
    tokenSuffix: '}'
    escapeType: xml
```
And then under Variables > Variable Groups I've got a linked variable group including a variable with name SQLConnectionToken however in the logs for this task it says `replaced 0 tokens out of 0 in 0 file(s) in 0.015 seconds.`

Can you recommend what I need to do to pick up my variables?
