### ISSUE TITLE
Allow to transfer parameters as ENV variables to task

### ISSUE THREAD

**Issue by Rabattkarte** [qetza/vsts-replacetokens-task#252]
In our pipelines, we have the following syntax on multiple occasions. This is because we are using the `replacetokens` task in pipeline step templates, where you are unable to define a `variables:` block and we must not call templates with magic numbers.

Please have a look at the following example:

#### replaceTemplate.yaml

```yaml

parameters:
  - name: myParam1
    type: string
  - name: myParam1
    type: string
  - name: myTargetFile
    type: string

steps:
  - checkout: self

  - bash: |
      echo "Using myParam1: ${{ parameters.myParam1 }}"
      echo "##vso[task.setvariable variable=myParam1]${{ parameters.myParam1 }}"

      echo "Using myParam1: ${{ parameters.myParam2 }}"
      echo "##vso[task.setvariable variable=myParam1]${{ parameters.myParam2 }}"
    displayName: Transfer params to vars for replacetokens task

  - task: replacetokens@4
    inputs:
      targetFiles: '${{ parameters.myTargetFile }}'
    displayName: 'Replace tokens in: ${{ parameters.myTargetFile }}'
```

My proposal would be a input parameter similar to [the Bash task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash)'s `bashEnvValue:`, using the example above:

#### replaceTemplate.yaml

```yaml

parameters:
  - name: myParam1
    type: string
  - name: myParam1
    type: string
  - name: myTargetFile
    type: string

steps:
  - checkout: self

  - task: replacetokens@4
    inputs:
      targetFiles: '${{ parameters.myTargetFile }}'
      replaceMapping:
        - myParam1: ${{ parameters.myParam1 }}
        - myParam2: ${{ parameters.myParam2 }}
    displayName: 'Replace tokens in: ${{ parameters.myTargetFile }}'
```

**Comment by qetza** [comment]
Hi @Rabattkarte,
Thanks for the feedback, i will think about the feasibility to add a parameter with a list of key/value and inject this as variables which are available for replacement.

**Comment by kwaazaar** [comment]
Sounds like a good plan @Rabattkarte.

I'm the author of #237 and run into a similar issue today. I'm doing the replacetokens from a template that receives the 'data' als parameters. In template files you cannot specify variables (unless used as a variables-template, but that's another thing). Specifying a mappingtable would be very handy for me, as I need to replace just 3 tokens.

**Comment by qetza** [comment]
Hi @Rabattkarte, @kwaazaar,
The latest version of the task allows you to supply inline variables using the YAML syntax so you can inject parameter values now like this:

```yaml
- task: qetza.replacetokens-dev.replacetokens-task.replacetokens@4
   displayName: 'inline variables'
   inputs:
     targetFiles: '*.json'
     inlineVariables: |
       myParam1: '${{ parameters.myParam1 }}'
       myParam2: '${{ parameters.myParam2 }}'
```
