### ISSUE TITLE
Error running task:  (Line: 65, Col: 3): Unexpected value 'encoding' 

### ISSUE THREAD

**Issue by jrowe88** [qetza/vsts-replacetokens-task#279]
I added the task to my yaml and when I run the build pipeline I get the following error:
```
/build/azure-pipelines-build.yml (Line: 65, Col: 3): Unexpected value 'encoding'
/build/azure-pipelines-build.yml (Line: 66, Col: 3): Unexpected value 'actionOnMissing'
/build/azure-pipelines-build.yml (Line: 67, Col: 3): Unexpected value 'keepToken'
/build/azure-pipelines-build.yml (Line: 68, Col: 3): Unexpected value 'enableTelemetry'
```

Any ideas?

My task definition is:
```
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace App Configuration connection token'
  encoding: utf-8
  actionOnMissing: continue
  keepToken: true
  enableTelemetry: false
  inputs:
    targetFiles: |
      **/App.config
      **/Web.config    
```
