### ISSUE TITLE
ActionOnMissing not logging warning

### ISSUE THREAD

**Issue by butlerpaul1** [qetza/vsts-replacetokens-task#290]
Hello we use the task to log a warning if a variable is not found, but this functionality doesn't seem to be wokring.

The logs indicate that the task reconigises that the variable is missing and to log a warning. Looking at the output could the syntax to log a warning be incorrect? Should it be `"##vso[task.logissue type=warning;]` , or is there anything wrong with the inputs I provide?

https://learn.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=powershell

2022-11-21T13:00:50.1310536Z ##[warning]  variable not found: EmulatorDbIp
2022-11-21T13:00:50.1312955Z ##[debug]Processed: ##vso[task.issue type=warning;]  variable not found: EmulatorDbIp
2022-11-21T13:00:50.1314132Z ##[debug]  EmulatorDbIp: 

![image](https://user-images.githubusercontent.com/10852870/203080029-9867893f-1aa0-4af0-b48c-186e37b30212.png)

```
task: replacetokens@5
displayName: 'Substitute Variables in Configuration Files'
inputs:
  rootDirectory: '${{ parameters.dropPath }}\${{ parameters.customerName }}-Configuration\'
  targetFiles: |
    **\*.csv
    **\*.xml
    **\*.config
    **\*.sql
    **\*.json
  encoding: 'auto'
  tokenPattern: 'octopus'
  writeBOM: true
  verbosity: 'detailed'
  actionOnMissing: 'warn'
  keepToken: false
  actionOnNoFiles: 'warn'
  enableTransforms: false
  enableRecursion: false
  useLegacyPattern: true
```
