### ISSUE TITLE
Variable not found

### ISSUE THREAD

**Issue by tucker87** [qetza/vsts-replacetokens-task#291]
I'm getting "variable not found: InstanceNumber" While InstanceNumber is working for the rest of the system. 

I added "inlineVariables: 'InstanceNumber: $(InstanceNumber)'" To see if that helped and it didn't have any effect.

Any help would be greatly appreciated.

**Top level**:
```
variables:
  - template: web/devVariables.yml@templates
  - name: InstanceNumber
    value: ''

stages:
  - template: web/buildStage.yml@templates
    parameters:
      projectName: SSO
      project: Bourbon.SSO\Bourbon.SSO.csproj
```

**Template**:
```
[...]
If($branch -Match "(feature|iteration)\/([A-Z,a-z,0-9]+)") {
        $branchNumber = $Matches.2
        Write-Host "##vso[task.setvariable variable=InstanceNumber]$branchNumber"
    }
[...]

- task: PowerShell@2
  displayName: 'Clear Instance Number for main'
  condition: eq(variables.IsMaster, True)
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "##vso[task.setvariable variable=InstanceNumber]"
[...]

- task: replacetokens@5
  inputs:
    targetFiles: 'X:\Websites\${{ parameters.projectName }}*\appsettings.Development.json'
    encoding: 'auto'
    tokenPattern: 'azpipelines'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    actionOnNoFiles: 'continue'
    enableTransforms: false
    inlineVariables: 'InstanceNumber: $(InstanceNumber)'
    enableRecursion: false
    useLegacyPattern: false
    enableTelemetry: true
```

Output:
```
Starting: replacetokens
==============================================================================
Task         : Replace Tokens
Description  : Replace tokens in files
Version      : 5.1.0
Author       : Guillaume Rouchon
Help         : [Learn more about this task](https://github.com/qetza/vsts-replacetokens-task/blob/master/ReplaceTokens/ReplaceTokensV4/README.md) (v5.1.0)
==============================================================================
loading inline variables:
  1 variable(s) loaded.
replacing tokens in: X:\Websites\SSO\appsettings.Development.json
##[warning]  variable not found: InstanceNumber
##[warning]  variable not found: InstanceNumber
##[warning]  variable not found: InstanceNumber
  0 token(s) replaced out of 3
replaced 0 tokens out of 3 in 1 file(s) in 88.209 seconds.
Finishing: replacetokens

```
