### ISSUE TITLE
Unable to replace a url variable value

### ISSUE THREAD

**Issue by ianadavies** [qetza/vsts-replacetokens-task#307]
Hi, I have a variable that has a URL in it which i need to replace.

The issue is that no matter what I try I always have the colon replaced with a double underscore. 

```"MyUrl": "https://#{HostName}#.myservice.azure.net/"```

Will transform to 

```"MyUrl": "https__//myhost.myservice.azure.net/"```

The same issue happens if I just have the whole URL in the variable e.g 

```"MyUrl": "#{HostUrl}#"```

I have tried all variants with `noescape(myVar)` and with escape type as `auto` and `none`

This is a json file that I am replacing tokens in.

Any help would be appreciated, thanks

**Comment by qetza** [comment]
Hi @ianadavies,
I couldn't reproduce your issue using the following file:
```json
{
  "MyUrl": "https://#{HostName}#.myservice.azure.net/"
}
```

and take configuration:
```yaml
- task: qetza.replacetokens.replacetokens-task.replacetokens@5
  displayName: 'replace tokens'
  inputs:
    rootDirectory: 'issue-307'
    targetFiles: config.json
    verbosity: detailed
```

Could you set verbosity to `detailed` and check the log to see the variable value which was used by the task:
![image](https://github.com/qetza/vsts-replacetokens-task/assets/8191369/8d03cc86-6897-4c70-8c96-b76ce507c851)

Make sure that it is not another task which is updating the file afterward.
