### ISSUE TITLE
Cannot replace inline variable

### ISSUE THREAD

**Issue by buisihung11** [qetza/vsts-replacetokens-task#321]
I'm facing an issue in that i couldn't get the value from the inline variable that was declared in the pipeline file. 

```yaml
variables:
  - template: templates/integrations/variables.yaml@pl-applications
    parameters:
      ENVIRONMENT: "dev"
  - name: SERCRET_VALUE
    value: ThisIsSecretvalue
````

The template file is just import an variable group, the replace token task can get the key in that variable group but cannot replace the SECRET_VALUE variable
