### ISSUE TITLE
Strange behaviour when replacing a date with specific format

### ISSUE THREAD

**Issue by byzent** [qetza/vsts-replacetokens-task#322]
When I try to replace string of a date (e.g. 2023-09-25) I get: ##[error]  variable not found: action_date
However if I change it to '223-09-25' or 'YYYY-MM-dd' the replace works correctly. I have no idea why the string '2023-09-25' doesn't work.

```
parameters:
  - name: targetFiles
     type: string

  - name: actionDate
    type: string

steps:
  - bash: |
      echo "Using actionDate: ${{ parameters.actionDate }}"
    displayName: Print parameter actionDate

  - task: qetza.replacetokens.replacetokens-task.replacetokens@4
    displayName: 'Replace Tokens'
    inputs:
      rootDirectory: '$(System.DefaultWorkingDirectory)/'
      targetFiles: ${{ parameters.targetFiles }}
      actionOnMissing: 'fail'
      actionOnNoFiles: 'continue'
      keepToken: false
      tokenPrefix: '#{'
      tokenSuffix: '}#'
      useLegacyPattern: false
      useLegacyEmptyFeature: true
      enableTelemetry: false
      verbosity: 'detailed'
      inlineVariables: |
        action_date: ${{ parameters.actionDate }}
```
    
The file where I want to do the replace:
`action_date: #{ action_date }#  `

**Comment by qetza** [comment]
Hi @byzent,
Your issue is in the declaration of the inline variables and how it is parsed by the `js-yaml` library the task is using: the YAML string passed to the library is `action_date: 2023-09-25` which is converted to JSON and as the value `2023-09-25` is read as a date type it is not loaded as variable.

To fix the issue just add single quotes around the parameter to force the value as a string:

```yaml
- task: qetza.replacetokens.replacetokens-task.replacetokens@4
  displayName: 'Replace Tokens'
  inputs:
    rootDirectory: '$(System.DefaultWorkingDirectory)/'
    targetFiles: ${{ parameters.targetFiles }}
    actionOnMissing: 'fail'
    actionOnNoFiles: 'continue'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    useLegacyPattern: false
    useLegacyEmptyFeature: true
    enableTelemetry: false
    verbosity: 'detailed'
    inlineVariables: |
      action_date: '${{ parameters.actionDate }}'
```
