### ISSUE TITLE
~ shortcut in TargetFiles not expanded consistently with how ADO Pipelines expands it

### ISSUE THREAD

**Issue by vanastassiou** [qetza/vsts-replacetokens-task#323]
Using `qetza.replacetokens.replacetokens-task.replacetokens@5` in an Azure DevOps pipeline, my target file is created in `/home/vsts/work/1/s/~/testfile.txt`.

However, when using the `~` shortcut elsewhere in the pipeline, it is expanded to `/home/vsts/`.

My YAML:

```
    - task: qetza.replacetokens.replacetokens-task.replacetokens@5
      displayName: 'Replace tokens in test file'
      inputs:
        targetFiles: test-template.txt=> ~/test.txt
        tokenPattern: 'custom'
        tokenPrefix: '__'
        tokenSuffix: '__'
        actionOnMissing: 'fail'
```
