### ISSUE TITLE
Using value of "**.**" for targetFiles attribute.

### ISSUE THREAD

**Issue by orenzp** [qetza/vsts-replacetokens-task#324]
Good Day,
Does the targetFiles attribute support using the value "**.**"? Im running the following configuration and im getting permissions errors on.git folder access.

```
task: qetza.replacetokens.replacetokens-task.replacetokens@4
  displayName: "Replace tokens"
  inputs:
    rootDirectory: "$(System.DefaultWorkingDirectory)/${{ variables.kitPath }}"
    targetFiles: "**/**"
    tokenPattern: 'custom'                               
    tokenPrefix: "[__"
    tokenSuffix: "__]"
    verbosity: 'detailed'
```
See attached error log [qatza_errors.txt](https://github.com/qetza/vsts-replacetokens-task/files/13062867/qatza_errors.txt)

Is there a way to exclude folders from being processed?

Thanks in advance for your help.
