### ISSUE TITLE
Wrong indentation when variable is multiline

### ISSUE THREAD

**Issue by trashhead** [qetza/vsts-replacetokens-task#326]
I have this variable defined in my azure pipeline.
```
  application.properties: |
    customMessage=This is dev machine
    customMessage2=This is dev machine2
```

I use it here:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-test-config
  namespace: elinstallation
data:
  application.properties: |
    #{application.properties}#

```

But this results in the following:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-test-config
  namespace: elinstallation
data:
  application.properties: |
    customMessage=This is dev machine
customMessage2=This is dev machine2

```

First line is ok but second has wrong indentation.

**Comment by qetza** [comment]
Hi @trashhead,
This is because of how YAML multiline values are read, the first spaces which represents the YAML indentation are stripped from your value on all lines.

So the YAML value for `application.properties` in

```yaml
application.properties: |
    customMessage=This is dev machine
    customMessage2=This is dev machine2
```

will be
```txt
customMessage=This is dev machine
customMessage2=This is dev machine2


```

(note the end of line at the end also)

If you need some spaces at the start of your lines you need to add it after the YAML indentation (your first line has the correct indentation because the indentation is in the file before the replace token)
```yaml
application.properties: |-
    customMessage=This is dev machine
        customMessage2=This is dev machine2
```

(the added `-` in the YAML will avoid adding a new line at the end of the value, see https://yaml-multiline.info/ for doing test)

**Comment by trashhead** [comment]
I see you have some functions implemented, upper, lower etc. Would it not be possible to add something similiar to "indent" which might take an argument of how much it should indent every row.
Would help alot :)

**Comment by qetza** [comment]
Hi @trashhead,
This could be an enhancement but then would you expect the first line to be also indented or only starting from the second line; as usually the token is already indented correctly so will be the first line.

So `#{indent(application.properties, 4)}#` with a value as you specified would be replaced by:
```
customMessage=This is dev machine
    customMessage2=This is dev machine2
```

and
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-test-config
  namespace: elinstallation
data:
  application.properties: |
    #{indent(application.properties, 4)}#
```

would become:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-test-config
  namespace: elinstallation
data:
  application.properties: |
    customMessage=This is dev machine
    customMessage2=This is dev machine2
    
```

note: the last empty line will also be indented
