### ISSUE TITLE
Documentation for targetFiles is not clear

### ISSUE THREAD

**Issue by jbrezina** [qetza/vsts-replacetokens-task#328]
The following form does not work in azure pipelines:
```
targetFiles: |
      **/*.config
      **/*.json => outputs/*.json
```
Semicolon separated patterns has to be used. Otherwise I get an error that no files has been found:
`##[error]found no files to process in 0.012 seconds.`

Could you make it clear in the description/README or fix the problem please?

**Comment by qetza** [comment]
Hi @jbrezina,
Can you provide more information as i cannot reproduce your issue.

Here is the pipeline is created to test:
```yaml
pool:
  vmImage: ubuntu-latest

variables:
  var1: value1
  var2: value2
  var3: value3

steps:
- task: qetza.replacetokens-dev.replacetokens-task.replacetokens@5
  displayName: 'replace tokens'
  inputs:
    rootDirectory: 'issue-328'
    targetFiles: |
      **/*.config
      **/*.json => outputs/*.json
    verbosity: detailed
```

And the executions finds both files:
![image](https://github.com/qetza/vsts-replacetokens-task/assets/8191369/1af459f4-5708-4d6c-a1f3-a86f2b2cdd17)

Instead of newline to separate paths you can use the comma character `,` ; i will update the documentation in the next version to fix this missing spec.

**Comment by jbrezina** [comment]
I had to use semicolon (not a colon) separated list to get it work as the pipe separated list got mi the error I mentioned above.
This works:
```yml
- task: replacetokens@5
  displayName: Replace tokens in configuration file(s)
  inputs:
    rootDirectory: ${{ parameters.BinariesPath }}
    targetFiles: '*.json;**/*.settings.json'
    encoding: 'utf-8'
    actionOnMissing: 'fail'
    actionOnNoFiles: 'fail'
    enableTelemetry: false
```
```yml
- task: replacetokens@5
  displayName: Replace tokens in configuration file(s)
  inputs:
    rootDirectory: ${{ parameters.BinariesPath }}
    targetFiles: |
      *.json
      **/*.settings.json
    encoding: 'utf-8'
    actionOnMissing: 'fail'
    actionOnNoFiles: 'fail'
    enableTelemetry: false
```
