### ISSUE TITLE
Transform fails with default arguments if azpipeline tokens are being used

### ISSUE THREAD

**Issue by codialsoftware** [qetza/vsts-replacetokens-task#332]
Following configuration will fail:
```
- task: qetza.replacetokens.replacetokens-task.replacetokens@5
  inputs:
    targetFiles: somefile.txt
    escapeType: none
    keepToken: true
    tokenPattern: azpipelines
    enableTransforms: true
    actionOnNoFiles: fail
    enableTelemetry: false

```
Content of `somefile.txt`:
```
setting = "$(lower(here-goes-variable-name))"
```

Task works fine, once different function transformation arguments tokens are being used. This works fine:
- config
```
- task: qetza.replacetokens.replacetokens-task.replacetokens@5
  inputs:
    targetFiles: somefile.txt
    escapeType: none
    keepToken: true
    tokenPattern: azpipelines
    enableTransforms: true
    transformPrefix: '['
    transformSuffix: ']'
    actionOnNoFiles: fail
    enableTelemetry: false
```
- somefile.txt
```
setting = "$(lower[here-goes-variable-name])"
```
